FROM gcc:12-bookworm

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /work/conan-recipes

RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake python3 python3-venv git \
    && rm -rf /var/lib/apt/lists/*

COPY test-astra      /work/conan-recipes/test-astra
COPY packages-linux  /work/conan-recipes/packages-linux
COPY gtest           /work/conan-recipes/gtest
COPY profiles        /work/conan-recipes/profiles
COPY extensions      /work/conan-recipes/extensions

RUN ./test-astra/setup.sh

RUN GCC_MAJOR=$(gcc -dumpversion | cut -d. -f1) && \
    sed -i "s/^compiler.version=.*/compiler.version=${GCC_MAJOR}/" profiles/astra-gcc && \
    cat profiles/astra-gcc

COPY test-astra/run_gtest.sh /work/conan-recipes/test-astra/run_gtest.sh
RUN chmod +x /work/conan-recipes/test-astra/run_gtest.sh

CMD ["bash", "-lc", "source /work/conan-recipes/venv/bin/activate && ./test-astra/run_gtest.sh"]
