FROM gcc:12-bookworm

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /work/conan-recipes

RUN apt-get update && apt-get install -y --no-install-recommends \
    cmake python3 python3-venv git perl pkg-config nasm \
    && rm -rf /var/lib/apt/lists/*

COPY test-astra      /work/conan-recipes/test-astra
COPY packages-linux  /work/conan-recipes/packages-linux
COPY profiles        /work/conan-recipes/profiles
COPY extensions      /work/conan-recipes/extensions
COPY zlib            /work/conan-recipes/zlib
COPY abseil          /work/conan-recipes/abseil
COPY c-ares          /work/conan-recipes/c-ares
COPY re2             /work/conan-recipes/re2
COPY protobuf        /work/conan-recipes/protobuf
COPY openssl         /work/conan-recipes/openssl
COPY grpc            /work/conan-recipes/grpc

RUN ./test-astra/setup.sh

RUN GCC_MAJOR=$(gcc -dumpversion | cut -d. -f1) && \
    sed -i "s/^compiler.version=.*/compiler.version=${GCC_MAJOR}/" profiles/astra-gcc && \
    cat profiles/astra-gcc

COPY test-astra/run_grpc.sh /work/conan-recipes/test-astra/run_grpc.sh
RUN chmod +x /work/conan-recipes/test-astra/run_grpc.sh

CMD ["bash", "-lc", "source /work/conan-recipes/venv/bin/activate && ./test-astra/run_grpc.sh"]
